### ISSUE TITLE
Error: Please add a title

### ISSUE THREAD

**Issue by prasad-takale-eminds** [strapi-community/strapi-tool-dockerize#91] opened 2023-08-11 09:35 UTC
## ⛔️  Error log

Command failed with exit code 1: yarn add mysql
[31m[1mUsage Error[22m[39m: The nearest package directory (/home/prasadtakale/beckn/strapi/strapi/beckn) doesn't seem to be part of the project declared in /home/prasadtakale/beckn/strapi/strapi.

- If /home/prasadtakale/beckn/strapi/strapi isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If /home/prasadtakale/beckn/strapi/strapi is intended to be a project, it might be that you forgot to list beckn in its workspace configuration.
- Finally, if /home/prasadtakale/beckn/strapi/strapi is fine and you intend beckn to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.

[1m$ [22myarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: yarn add mysql
[31m[1mUsage Error[22m[39m: The nearest package directory (/home/prasadtakale/beckn/strapi/strapi/beckn) doesn't seem to be part of the project declared in /home/prasadtakale/beckn/strapi/strapi.

- If /home/prasadtakale/beckn/strapi/strapi isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If /home/prasadtakale/beckn/strapi/strapi is intended to be a project, it might be that you forgot to list beckn in its workspace configuration.
- Finally, if /home/prasadtakale/beckn/strapi/strapi is fine and you intend beckn to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.

[1m$ [22myarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
    at makeError (/home/prasadtakale/.npm/_npx/a642ee8303c0fc2f/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/prasadtakale/.npm/_npx/a642ee8303c0fc2f/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installDependecies (/home/prasadtakale/.npm/_npx/a642ee8303c0fc2f/node_modules/@strapi-community/dockerize/core/dependencies.js:21:3)
    at async /home/prasadtakale/.npm/_npx/a642ee8303c0fc2f/node_modules/@strapi-community/dockerize/index.js:63:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v18.16.1
- 💻  OS: linux x64

**Comment by Eventyret** [comment] 2023-08-11 09:56
Seems you run the tool in the wrong folder or gave it the wrong folder. Closing as it's not a bug

**Closed** 2023-08-11 09:56 UTC
